### PR TITLE
feat: Products (dex) and Rate (trav)

### PR DESCRIPTION
**Pull request by deziiii**

### CODE REVIEW

**Comment by deziiii** [comment]
For product to show in the filter_products page, when creating the product, must use these categories (case sensitive)
1) Tyres
2) Car Camera
3) Battery
4) Car Shampoo
5) Sound Processor
6) Engine Oil
7) Car Polish
8) Coilover
9) Brake Kit
10) Paint Protection
11) Rims 
12) Speakers

**Review by taronaeo — COMMENTED** [review]
```
user = User(
          args['email'],
          args['full_name'],
          args['password'],
          args['phone_number'],

          uid = args['email'],
          training_complete=args['training_complete'],
          background_check=args['background_check'],
        )

        db[args['email']] = user
        return user.__dict__
```

why are these deleted?

other remarks:
a. i think we can leave the product create page for the admins only cus users don't really need to sell their product there

b. products listing should preferably be contained in it's own file, instead of using listing.py as well

**Comment by deziiii** [comment]
Oh i thought the user one wasnt used and it kept throwing errors so i deleted it my bad

**Comment by deziiii** [comment]
Also the product create i put a notice for only admins so i was thinking we only make the users with acess level admin be able to use it

**Comment by taronaeo** [comment]
> Also the product create i put a notice for only admins so i was thinking we only make the users with acess level admin be able to use it

yep so we can check something like db_user[user.uid].access_level = 'Administrator' or something of that sort

**Review by taronaeo — DISMISSED** [review]
LGTM

**Review by WhataTravesty — DISMISSED** [review]
LGTM

**Review by WhataTravesty — APPROVED** [review]
LGTM

**Pull request merged**
